spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 1234
      hikari:
        connection-timeout: 20000
        maximum-pool-size: 5

